export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const CONVERSATION_LIST_FAIL = 'CONVERSATION_FAIL'
export const CONVERSATION_LIST_SUCCESS = 'CONVERSATION_SUCCESS'

export const FAIL = 'REGISTRATION_FAIL'
export const SUCCESS = 'REGISTRATION_SUCCESS'

export const MESSAGE_SENT_SUCCESS = 'MESSAGE_SENT_SUCCESS'
export const MESSAGE_SENT_FAIL = 'MESSAGE_SENT_FAIL'

export const MESSAGES_GET_SUCCESS = 'MESSAGES_GET_SUCCESS'
export const MESSAGES_GET_FAIL = 'MESSAGES_GET_FAIL'

export const MESSAGES_IMAGE_SEND_SUCCESS = 'MESSAGES_IMAGE_GET_SUCCESS'
export const MESSAGES_IMAGE_SEND_FAIL = 'MESSAGES_IMAGE_GET_FAIL'